# default profile
server:
  port: 8082
  servlet:
    context-path: /api/v1/
management:
  # http://localhost:8082/api/v1/actuator/mappings
  endpoints:
    web:
      exposure:
        include: mappings
app:
  kafka:
    topics:
      task5: task5-topic
    groups:
      task5: task5-group
    retry:
      # Частота запуска планировщика для повторной обработки сообщений из таблицы task5_dlq_messages.
      rate-ms: 60000
      # Максимальное количество попыток для транзиентных(временных) ошибок - недоступна Kafka,сеть,БД и т.д.
      max-attempts: 3
spring:
  application:
    name: shortcut-kafka-consumer
  docker:
    # Only for development
    # Если docker образа не существует, Spring Boot автоматически скачает и создаст его при запуске приложения.
    # Для локальной разработки. Spring Boot будет сам следить за тем, чтобы база данных была «жива»,
    # Rогда вы нажимаете кнопку Run/Stop, контейнер kafka_postgres будет автоматически запущен, а при остановке приложения — остановлен.
    # Как это работает.
    # Когда вы запускаете приложение:
    # - Spring ищет в корне проекта файлы типа postgresql-docker-compose.yml или compose.yaml.
    # - Вызывает postgresql-docker-compose.yml.
    # - Spring автоматически подменяет spring.datasource.url, username и password, считывая их прямо из вашего YAML-файла.
    #   Вам даже не нужно прописывать их в application.yml вручную!
    # - При остановке приложения Spring делает docker-compose stop.
    compose:
      file: postgresql-docker-compose.yml # Указываем ваш конкретный файл
      lifecycle-management: start_and_stop # Останавливать контейнер при выключении приложения
      readiness:
        tcp:
          connect-timeout: 10s # Ждать, пока база реально поднимется
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  # # Need because you can run app by "java -jar shortcutkafkaconsumer-0.0.1-SNAPSHOT.jar"
  datasource:
    url: jdbc:postgresql://localhost:5434/docker_kafka_consumer_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:9092
    topic-name: dev-topic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true # Важно для корректного восстановления из DLQ
    consumer:
      # Для ключа используем обычный StringDeserializer, так как там редко бывают ошибки
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # ErrorHandlingDeserializer решает classic Kafka problem: broken JSON
      # Consumer не падает. При ошибке десериализации отправляет сообщение в DLQ
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: "com.gmail.alexei28.shortcutkafkaconsumer.task5.dto.UserDto"
        spring.json.trusted.packages: "*"
        spring.json.remove.type.headers: false
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace
  org.springframework.kafka: info
  # Именно этот логгер покажет ошибку десериализации
  org.springframework.kafka.support.serializer: DEBUG
  # Этот логгер покажет процесс работы ErrorHandler и Recoverer
  org.springframework.kafka.listener.DeadLetterPublishingRecoverer: DEBUG
